project:
  type: book
  output-dir: _book
  
book:
  title: "Local Ecosystem accounts - a technical guidebook" 
  author:
  - name: "Willeke Anna Josephina A'Campo"
  - name: "Anders Lorentzen Kolstad"
  description: | 
    NINAs Technical Guidebook for Local-Scale Ecosystem Accounting Projects
  repo-url: https://github.com/NINAnor/EAguide
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: Data management
      chapters:
        - data-management/data-management-plan.qmd
        - data-management/data-publishing.qmd
        - data-management/naming-convention.qmd
    - part: Field surveys 
      chapters:
        - field-surveys/field-surveys.qmd
        - field-surveys/intro-to-qfield.qmd
        - field-surveys/qfield-nin.qmd
        - field-surveys/qfield-biodiversity-metrics.qmd
        - field-surveys/qfield-bgf.qmd
        - field-surveys/rshiny-carbon-calculator.qmd
    - part: Remote sensing
      chapters:
        - remote-sensing/remote-sensing.qmd
  appendices:
    - appendix/appendix-notes.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    number-sections: false 
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
