project:
  type: book
  output-dir: _book
  
book:
  title: "Local Ecosystem accounts - a technical guidebook" 
  author:
  - name: "Willeke Anna Josephina A'Campo"
  - name: "Anders Lorentzen Kolstad"
  description: | 
    NINAs Technical Guidebook for Local-Scale Ecosystem Accounting Projects
  repo-url: https://github.com/NINAnor/EAguide
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - field-surveys/field-surveys.qmd
    - remote-sensing/remote-sensing.qmd
    - naming-convention/naming-convention.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    
    code-link: true

bibliography: references.bib
csl: NINArefStyle.csl
