project:
  type: book
  output-dir: _book

book:
  title: "Local Ecosystem accounts - a technical guidebook" 
  subtitle: "Finskala Naturregnskap - en teknisk håndbok"
  author:
  - name: "Willeke A'Campo"
  - name: "Anders Lorentzen Kolstad"
  description: | 
    NINAs Technical Guidebook for Local-Scale Ecosystem Accounting Projects
  repo-url: https://github.com/NINAnor/EAguide
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - project-management/project-management.qmd
    - part: QGIS
      chapters:
        - qgis/qgis-installation.qmd
        - qgis/qfield-intro.qmd
        - qgis/qgis-plugins.qmd
        - qgis/qgis-background-maps.qmd
    - part: data-collection/data-collection.qmd
      chapters:
        - data-collection/field-surveys/qfield-nin.qmd
        - data-collection/field-surveys/qfield-bm.qmd
        - data-collection/field-surveys/qfield-bgf.qmd
        - data-collection/field-surveys/rshiny-carbonviewer.qmd
    - data-analysis/data-analysis.qmd
    - data-publishing/data-publishing.qmd
    - documentation/documentation.qmd
    - part: FAIR Data Management
      chapters:
        - fair-data/fair-principles.qmd
        - fair-data/naming-convention.qmd
  appendices:
    - appendix/appendix-notes.qmd
  sidebar:
    collapse-level: 1

margin-footer: | 
  <small><em style="font-size: 0.75em;">Content on this page has been partially created using AI services from OpenAI and GitHub Copilot. All content is quality assured by NINA employees before publication.</em></small>

format:
  html: 
    theme: 
    - cosmo
    - NINAstyle.scss
    number-sections: false 
    code-link: true
    toc-depth: 3

bibliography: references.bib
csl: NINArefStyle.csl
