# QGIS and QField introduction {#sec-intro-to-qfield}

**QGIS** is an open-source desktop GIS application and **QField** is it's mobile twin that allows you to take your QGIS projects into the field and collect data. **QField Cloud** is a cloud-based service that allows you to synchronize your QGIS projects with your QField projects. 

Several QField projects exists which are useful within ecosystem accounting. 
A QField project (also called a QField or QGIS template) is a QGIS project file made in QGIS that is optimized for use in the QField app. This project file is  transferred to your mobile device and opened in the QField app.

The page [Field Surveys](#sec-field-surveys) provides a list of QField projects that are useful for ecosystem accounting and their specific instructions on how to install and use them. This page provides a general introduction to QGIS, QField and QField Cloud and how they can be used to transfer your project data between QGIS and QField.

## Prerequisites

- [QGIS v3.x](https://qgis.org/en/site/index.html) installed on your computer.
- [QField](https://qfield.org/) installed on your device.
    - [Google Play](https://play.google.com/store/apps/details?id=ch.opengis.qfield) 
    - [Apple App Store](https://apps.apple.com/us/app/qfield-for-qgis/id1531726814).
- A [QField Cloud](https://qfield.cloud/) account.
    - Sign up for an account using your NINA email address [here](https://app.qfield.cloud/accounts/signup/).
    - Send and email to NINA's **datahjelp** for access to the NINAnor QField Cloud organization and ask to be added to the *Fieldwork* group.

Once you have installed QGIS on your computer. Go to  *Plugins > Manage and Install Plugins > All*  and install the following plugins in QGIS:

- [QFieldSync](https://plugins.qgis.org/plugins/qfieldsync/): a QGIS plugin that allows you to synchronize your QGIS projects with QField Cloud.

Other useful plugins:

- [NiB-ortofoto-prosjekt](https://plugins.qgis.org/plugins/get_nib-main/): a Q GIS plugin that allows you to add high-resolution aerial photos from the Norwegian Mapping Authority (Kartverket) and use them as a background (WMS) layer  in your QGIS project. It finds all available aerial photos for the area you are working in and adds them to your project.
- ...
- ...

**Table: overview of QField projects available on NINAnor's QField Cloud organization.**

| Project name | Description | Instructions |
|--------------|-------------|--------------|
| [QField project 1](#sec-qfield-project-1) | Description of project 1 | [Instructions](#sec-qfield-project-1) |
| [QField project 2](#sec-qfield-project-2) | Description of project 2 | [Instructions](#sec-qfield-project-2) |
| [QField project 3](#sec-qfield-project-3) | Description of project 3 | [Instructions](#sec-qfield-project-3) |





