# NiN 2.0 Naturtype Mapping {#sec-nin}

The NiN 2.0 mapping protocol is used to map and register naturetypes in Norway. Knowledge on species and naturtype mapping is a prerequisite for mapping NiN. This guide provides a technical overview of the QField app used for fieldmapping. Official documentation on the NiN 2.0 mapping protocol can be found on the [Artsdatabanken website](https://www.artsdatabanken.no/Pages/266884/Veiledere_for_terrestrisk_kartlegging).

:::{.note}
**Note** that this QField Template is designed for mapping NiN 2.0. From 2026 onwards NiN 3.0 will be used as mapping protocol. As of today, there is no QGIS Template available for NiN 3.0. 
:::

## User Guide

#### Install NiN QField on your tablet

The **NiN 2.0** QGIS template is uploaded to NINA's QField Cloud account. For general instructions on QGIS, QField and QField Cloud follow the guide: [QGIS and QField introduciton](intro-to-qfield.qmd).

1. Open QField on your tablet and go to `QFieldCloud projects` > `My Projects` 
2. Select the project and the latest version of the project will be downloaded to your tablet.
    - **nin2_project_name_year**: project specific NiN mapping template.
    - **nin2_norge_2024**: NiN mapping template for the whole of Norway.

    *It can take up to several minutes to download your project*

3. Set your user name in the QField app. This ensures that your name is automatically added to the `kartlegger` field in the attribute table, every time you map a new naturtype.
    - Go to `Settings` > `Settings` > `Variables` 
    - Add a new variable `qfield_user_name` with your name `firstname.lastname`

4. Read the PDF instructions, especially chapter 3 "Kartlegging av NiN-Naturtyper"

## Developer Guide

#### How to create a new NiN 2.0 template for a new project area? 

You can create a new template for a new mapping area by using the NiN 2.0 mapping template for the whole of Norway. Here you need to add your study area polygon and offline background maps. 

0. Read the PDF instructions, especially chapter 2 "Installering og oppstart".

1. Download the qfield_nin2_norge QField template from [NiN_QGIS_3.x](https://github.com/NINAnor/NiN_QGIS_3.x) repository.

2. Create a new polygon layer `study_area` and save it to `vector/%project_name%_misc.gpkg` GPKG and add it to the `Area` group. 

3. Download raster files in `GeoTIFF` format from [høydedata.no](https://hoydedata.no/) and [norgeibilder.no](https://www.norgeibilder.no/). 
    - DTMs and DSMs: [høydedata.no](https://hoydedata.no/)
    - Ortophotos (RGB and CIR): [norgeibilder.no](https://www.norgeibilder.no/)
        - Login with your Geonorge GeoID
        - enter study area bounding box coordinates 
        - Coordinate system: UTM 33
        - clip by bounding box 
        - send order

4. Convert your rasters to Cloud Optimized GeoTiffs. Shell scripts can be found [here](https://github.com/NINAnor/NiN_QGIS_3.x/tree/master/qfield_nin2_norge/scripts).

5. Add your downloaded raster files as offline map layers in QField. 

6. Upload your new project to QField Cloud and invite the fieldworkers (collaborators) to the project. 

#### Change log: 

We forked the NiN 2.0 Template from the [GitHub ](https://github.com/geco-nhm/NiN_QGIS_3.x) repository developed by the University of Oslo. Changes made to orginal template are documented [here](https://github.com/NINAnor/NiN_QGIS_3.x/blob/master/CHANGELOG.md). 

### NINA Contacts

::: {.columns}
::: {.column}
**NiN:**

- Trond Simensen
- Erik Stange
- Anders Lyngstad
:::

::: {.column}
**QGIS/QField Cloud managers:**

- Willeke A'Campo 
- Stig Claussen
:::
:::