
# Data Collection {#sec-data-collection}
This page presents a list of field surveys and remote sensing data sources usefull for ecosystem accounting projects.  

## Field surveys {#sec-field-surveys}

This page presents a list of field surveys and applications usefull for ecosystem accounting projects.   

**Available Field Applications:**

- [NiN 2.0 Naturetype Mapping](./field-surveys/qfield-nin.qmd)
- [Biodiversity Metric 4.0](./field-surveys/qfield-bm.qmd)
- [Blue Green Factor](./field-surveys/qfield-bgf.qmd)
- [Carbon Viewer](./field-surveys/rshiny-carbonviewer.qmd)

<br>

| Field Application | Tool | Instructions | Download |
| :---------------- | :--- | :----------- | :------- |
| **NiN 2.0** <br> **Naturetype Mapping**| QGIS/QField | [PDF Instructions](https://github.com/geco-nhm/NiN_QGIS_3.x/blob/master/NHM_Rapport_83_QGIS_NiN_2019.pdf) | [NINAnor/NiN_QGIS_3.x](https://github.com/NINAnor/NiN_QGIS_3.x) |
| **Biodiversity Metric 4.0** | QGIS/QField | • [GIS tools User Guide (PDF)](https://publications.naturalengland.org.uk/publication/6049804846366720) <br> • [Data Standard (XLSX)](https://publications.naturalengland.org.uk/publication/6049804846366720) | [NINAnor/BiodiversityMetric_QGIS_3.x](https://github.com/NINAnor/BiodiversityMetric_QGIS_3.x) |
| **Bluegreen Factor** | QGIS/QField | • [App Instructions](./field-surveys/qfield-bgf.qmd) |  [NINAnor/BGF-QGIS](https://github.com/NINAnor/BGF-QGIS) | 
| **CarbonViewer** | RShiny | • [App Instructions](https://carbonviewer.nina.no/)  <br> • [Publication](https://ntnuopen.ntnu.no/ntnu-xmlui/bitstream/handle/11250/3099192/KyrkjeeideAcalculatorCarbonManagement2023gull.pdf?sequence=1&isAllowed=y) | • [NINAnor/carbonviewer](https://github.com/NINAnor/carbonviewer) <br> • [carbonviewer.nina.no](https://carbonviewer.nina.no/)|

<br>

## Remote sensing {#sec-remote-sensing}

- Add usefull sources for EA.



